---
apiVersion: v1
data:
  CONSUL_HTTP_ADDR: http://consul.peekay.svc.cluster.local:8500
  JAVA_OPTION_COMMONS_WEB_SECURITY_CORS_ALLOW_CREDENTIALS: -Dfoo.commons.web.security.cors.allowCredentials=true
  JAVA_OPTION_COMMONS_WEB_SECURITY_CORS_ALLOWED_HEADERS: -Dfoo.commons.web.security.cors.allowedHeaders=*
  JAVA_OPTION_COMMONS_WEB_SECURITY_CORS_ALLOWED_METHODS: -Dfoo.commons.web.security.cors.allowedMethods=*
  JAVA_OPTION_COMMONS_WEB_SECURITY_CORS_ALLOWED_URIS: -Dfoo.commons.web.security.csrf.allowedUris=.*
  JAVA_OPTION_FOO_COMMONS_WEB_SECURITY_CORS_ALLOWED_ORIGINS: -Dfoo.commons.web.security.cors.allowedOrigins=*
  JAVA_OPTION_SECURITY_ENABLE_CSRF: -Dsecurity.enable-csrf=false
  JAVA_OPTION_SERVER_PORT: -Dserver.port=8080
  OAUTH2_ADMINID: foo.admin
  OAUTH2_ADMINSECRET: foo.admin.secret
  FOO_CACHE_CONFIG_DISTRIBUTEDCACHE: "true"
  FOO_COMMONS_WEB_SECURITY_CORS_allowedOrigins: '*'
  FOO_DATABASE_DATABASESERVERNAME: postgres
  FOO_DATABASE_SCHEMA: ${application.schema}
  FOOLOGROOT: ""
  SPRING_CLOUD_CONSUL_DISCOVERY_PREFERIPADDRESS: "true"
  SPRING_CLOUD_CONSUL_ENABLED: "true"
  SPRING_DATASOURCE_DRIVER-CLASS-NAME: org.postgresql.Driver
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/SharedServices?currentSchema=${application.schema}
  USE_CONSUL_AGENT: "false"
kind: ConfigMap
metadata:
  annotations:
    foo.com/duname: dkrconsul,dkrsdatasvr
    foo.com/duversion: 1.0.10-20190924.1569322386727,11.4.250002-20190924.1569322027243
    foo.com/version: 1.0.10,11.4.250002
  name: foo-java-config
