---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: themecontent
    foo.com/duversion: 1.4.104-20190925.1569388178838
    foo.com/version: 1.4.104
  labels:
    app.kubernetes.io/name: themecontent
    helm.sh/chart: themecontent-1.4.104
  name: themecontent
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: themecontent
  type: ClusterIP
