---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: dkrrabbitmq
    foo.com/duversion: 3.7.110004-20190924.1569322687372
    foo.com/version: 3.7.110004
  labels:
    app.kubernetes.io/name: rabbitmq
    helm.sh/chart: rabbitmq-3.7.110004
  name: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: amqp
  - name: management
    port: 15672
    protocol: TCP
    targetPort: management
  selector:
    app.kubernetes.io/name: rabbitmq
  type: ClusterIP
