---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: cas-row-sets
    foo.com/duversion: 2.5.12-20190923.1569266193622
    foo.com/version: 2.5.12
  labels:
    app.kubernetes.io/name: casrowsets
    helm.sh/chart: casrowsets-2.5.12
  name: casrowsets
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: casrowsets
  type: ClusterIP
