---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    foo.com/duname: dmdplin
    foo.com/duversion: 1.7.97-20190924.1569378293749
    foo.com/version: 1.7.97
  labels:
    app.kubernetes.io/name: foolineage
    helm.sh/chart: foolineage-1.7.97
  name: foolineage
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foolineage
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foolineage
        app.kubernetes.io/name: foolineage
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        - configMapRef:
            name: foo-java-config
        image: repo.foo.com/dmdatap-125.0.0-x64_redhat_linux_7-docker-prod/foo-lineage:1.7.97-20190924.1569378293749
        imagePullPolicy: IfNotPresent
        name: foolineage
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      initContainers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        image: docker.foo.com/yesbut/init-blocker:1.7
        name: init-blocker
