
builds:
- env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
    - windows
  goarch:
    - amd64
  ldflags:
    - -s -w -X github.com/hornpolish/ky/cmd.version={{.Version}} -X github.com/hornpolish/ky/cmd.commit={{.ShortCommit}} -X github.com/hornpolish/ky/cmd.date={{.Date}}

archives:
- replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'

brews:
  -
    tap:
      owner: hornpolish
      name: homebrew-brew
  description: A kubernetes yaml swiss army knife.
  homepage: https://github.com/hornpolish/ky
  test: |
    system "#{bin}/ky version"
