---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: dmprofilesvc
    foo.com/duversion: 4.5.79-20190924.1569376682518
    foo.com/version: 4.5.79
  labels:
    app.kubernetes.io/name: dataprofiles
    helm.sh/chart: dataprofiles-4.5.79
  name: dataprofiles
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: dataprofiles
  type: ClusterIP
