---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    foo.com/duname: geo-enhancement
    foo.com/duversion: 1.6.7-20190923.1569266256796
    foo.com/version: 1.6.7
  labels:
    app.kubernetes.io/name: geoenrichment
    helm.sh/chart: geoenrichment-1.6.7
  name: geoenrichment
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: geoenrichment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: geoenrichment
        app.kubernetes.io/name: geoenrichment
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        - configMapRef:
            name: foo-java-config
        image: repo.foo.com/vcmnfnd-135.0.0-x64_redhat_linux_7-docker-prod/foo-geo-enrichment:1.6.7-20190923.1569266256796
        imagePullPolicy: IfNotPresent
        name: geoenrichment
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      initContainers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        image: docker.foo.com/yesbut/init-blocker:1.7
        name: init-blocker
