---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: tenant
    foo.com/duversion: 1.10.9-20190909.1568068601957
    foo.com/version: 1.10.9
  labels:
    app.kubernetes.io/name: tenant
    helm.sh/chart: tenant-1.10.9
  name: tenant
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: tenant
  type: ClusterIP
