---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    foo.com/duname: credentials
    foo.com/duversion: 1.20.0-20190918.1568830153329
    foo.com/version: 1.20.0
  labels:
    app.kubernetes.io/name: credentials
    helm.sh/chart: credentials-1.20.0
  name: credentials
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: credentials
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: credentials
        app.kubernetes.io/name: credentials
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        - configMapRef:
            name: foo-java-config
        image: repo.foo.com/dmdatap-125.0.0-x64_redhat_linux_7-docker-prod/foo-credentials:1.20.0-20190918.1568830153329
        imagePullPolicy: IfNotPresent
        name: credentials
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      initContainers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        image: docker.foo.com/yesbut/init-blocker:1.7
        name: init-blocker
