---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: credentials
    foo.com/duversion: 1.20.0-20190918.1568830153329
    foo.com/version: 1.20.0
  labels:
    app.kubernetes.io/name: credentials
    helm.sh/chart: credentials-1.20.0
  name: credentials
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: credentials
  type: ClusterIP
