---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: comments
    foo.com/duversion: 2.6.16-20190917.1568709087672
    foo.com/version: 2.6.16
  labels:
    app.kubernetes.io/name: comments
    helm.sh/chart: comments-2.6.16
  name: comments
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: comments
  type: ClusterIP
