---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    foo.com/duname: dmdatahub
    foo.com/duversion: 1.5.102-20190924.1569378298288
    foo.com/version: 1.5.102
  labels:
    app.kubernetes.io/name: foodataexplorer
    helm.sh/chart: foodataexplorer-1.5.102
  name: foodataexplorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: foodataexplorer
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: foodataexplorer
        app.kubernetes.io/name: foodataexplorer
    spec:
      containers:
      - env:
        - name: JAVA_OPTION_FJPCP
          value: -Djava.util.concurrent.ForkJoinPool.common.parallelism=16
        envFrom:
        - configMapRef:
            name: foo-shared-config
        - configMapRef:
            name: foo-java-config
        image: repo.foo.com/dmdatap-125.0.0-x64_redhat_linux_7-docker-prod/foo-dataexplorer:1.5.102-20190924.1569378298288
        imagePullPolicy: IfNotPresent
        name: foodataexplorer
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      initContainers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        image: docker.foo.com/yesbut/init-blocker:1.7
        name: init-blocker
