---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: dmdatahub
    foo.com/duversion: 1.5.102-20190924.1569378298288
    foo.com/version: 1.5.102
  labels:
    app.kubernetes.io/name: foodataexplorer
    helm.sh/chart: foodataexplorer-1.5.102
  name: foodataexplorer
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: foodataexplorer
  type: ClusterIP
