---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    foo.com/duname: audit
    foo.com/duversion: 1.16.13-20190909.1568058546912
    foo.com/version: 1.16.13
  labels:
    app.kubernetes.io/name: audit
    helm.sh/chart: audit-1.16.13
  name: audit
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: audit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: audit
        app.kubernetes.io/name: audit
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        - configMapRef:
            name: foo-java-config
        image: repo.foo.com/va-125.0.0-x64_redhat_linux_7-docker-prod/foo-audit:1.16.13-20190909.1568058546912
        imagePullPolicy: IfNotPresent
        name: audit
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
      initContainers:
      - envFrom:
        - configMapRef:
            name: foo-shared-config
        image: docker.foo.com/yesbut/init-blocker:1.7
        name: init-blocker
