---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: reportdistribution
    foo.com/duversion: 2.7.76-20190925.1569390025144
    foo.com/version: 2.7.76
  labels:
    app.kubernetes.io/name: reportdistribution
    helm.sh/chart: reportdistribution-2.7.76
  name: reportdistribution
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: reportdistribution
  type: ClusterIP
