---
apiVersion: v1
kind: Service
metadata:
  annotations:
    foo.com/duname: filesservice
    foo.com/duversion: 2.10.4-20190910.1568136785094
    foo.com/version: 2.10.4
  labels:
    app.kubernetes.io/name: files
    helm.sh/chart: files-2.10.4
  name: files
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/name: files
  type: ClusterIP
