---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dkrcasall-permstore
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local-nfs
